G9L.Wedsite/Controllers/ExportController.cs
using G9L.Data.Enum;
using G9L.Data.ViewModel.Catalog.Export;
using G9L.IntergrationAPI.Export;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace G9L.Wedsite.Controllers
{
    public class ExportController : Controller
    {
        private readonly IExportApiClient _exportApiClient;
        public ExportController(IExportApiClient exportApiClient)
        {
            _exportApiClient = exportApiClient;
        }

        public async Task<IActionResult> Index(string KeyWord, IsExport? IsExport, DateTime? DateFrom, DateTime? DateTo, int PageIndex = 1, int PageSize = 1000)
        {

            var request = new GetManagerExportRequest()
            {
                KeyWord = KeyWord,
                IsExport = IsExport,
                DateFrom = DateFrom,
                DateTo = DateTo,
                PageIndex = PageIndex,
                PageSize = PageSize
            };

            var data = await _exportApiClient.GetListToExport(request);


            var rs = new List<GetIsExport>()
            {
                 new GetIsExport(){ ID = Data.Enum.IsExport.SuccessExport , Name = "Đã duyệt đơn hàng"},
                 new GetIsExport(){ ID = Data.Enum.IsExport.UnSuccessExport , Name = "Chưa duyệt đơn hàng"}
            };

            ViewBag.IsExport = rs.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.ID.ToString(),
                Selected = IsExport == x.ID
            });

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }
            return View(data);
        }
    }
}

G9L.Wedsite/Controllers/ImportController.cs
using G9L.Data.Enum;
using G9L.Data.ViewModel.Catalog.Import;
using G9L.IntergrationAPI.Import;
using G9L.IntergrationAPI.Provider;
using G9L.Wedsite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace G9L.Wedsite.Controllers
{
    public class ImportController : Controller
    {
        private readonly IImportApiClient _importApiClient;
        private readonly IProviderApiClient _providerApiClient;
        public ImportController(IImportApiClient importApiClient, IProviderApiClient providerApiClient)
        {
            _providerApiClient = providerApiClient;
            _importApiClient = importApiClient;
        }
        public async Task<IActionResult> Index(string KeyWord, int? ProviderID, DateTime? DateFrom, DateTime? DateTo, int PageIndex = 1, int PageSize = 1000)
        {
            var request = new GetManagerImportRequest()
            {
                KeyWord = KeyWord,
                ProviderID = ProviderID,
                DateFrom = DateFrom,
                DateTo = DateTo,
                PageIndex = PageIndex,
                PageSize = PageSize
            };

            var data = await _importApiClient.GetListToImport(request);

            var pr = await _providerApiClient.GetToProvideOnNameAndID();
            ViewBag.Provider = pr.Select(x => new SelectListItem()
            {
                Text = x.ProviderName,
                Value = x.ProviderID.ToString(),
                Selected = ProviderID == x.ProviderID
            });

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }
            return View(data);
        }
        public async Task<IActionResult> IndexUpdate(int ImportID)
        {
            var data = await _importApiClient.GetListImportAndImportDetails(ImportID);

            ViewBag.Import = ImportID;
            
            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }
            return View(data);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] GetAddImport request, GetAddImport.GetQuantily quantily, GetAddImport.GetProduct product, GetAddImport.GetIsUnit isUnit, GetAddImport.GetCostPrice costPrice)
        {

            var getQuantily = new int?[]
            {
                quantily.Quantily_1,
                quantily.Quantily_2,
                quantily.Quantily_3,
                quantily.Quantily_4,
                quantily.Quantily_5,
                quantily.Quantily_6,
                quantily.Quantily_7,
                quantily.Quantily_8,
                quantily.Quantily_9,
                quantily.Quantily_10
            };
            var getProduct = new int?[]
            {
                product.ProductID_1,
                product.ProductID_2,
                product.ProductID_3,
                product.ProductID_4,
                product.ProductID_5,
                product.ProductID_6,
                product.ProductID_7,
                product.ProductID_8,
                product.ProductID_9,
                product.ProductID_10,
            };                   
            var getIsUnit = new IsUnit?[]
            {
                isUnit.IsUnit_1,
                isUnit.IsUnit_2,
                isUnit.IsUnit_3,
                isUnit.IsUnit_4,
                isUnit.IsUnit_5,
                isUnit.IsUnit_6,
                isUnit.IsUnit_7,
                isUnit.IsUnit_8,
                isUnit.IsUnit_9,
                isUnit.IsUnit_10
            };
            var getCostPrice = new decimal?[]
            {
                costPrice.CostPrice_1,
                costPrice.CostPrice_2,
                costPrice.CostPrice_3,
                costPrice.CostPrice_4,
                costPrice.CostPrice_5,
                costPrice.CostPrice_6,
                costPrice.CostPrice_7,
                costPrice.CostPrice_8,
                costPrice.CostPrice_9,
                costPrice.CostPrice_10,
            };

            for (int i = 0; i < getProduct.Length; i++)
            {
                if (getProduct[i] is 0 or null)
                {
                    break;
                }
                for (int j = i + 1; j <= getProduct.Length; j++)
                {
                    if (getProduct[j] is 0 or null)
                    {
                        break;
                    }
                    if (getProduct[i] == getProduct[j])
                    {
                        await _importApiClient.DeleteToImport(request.ImportID);
                        TempData["Error"] = MessageModel.AddImtemFaledDuplicate();
                        return RedirectToAction("Index");
                    }
                }
            }
            int numberSussces = 0;
            for (int i = 0; i < getProduct.Length; i++)
            {
                if (getProduct[i] is 0 or null)
                {
                    break;
                }
                var data = new GetCreateImportDetailsRequest()
                {
                    ImportID = request.ImportID,
                    ProductID = (int)getProduct[i],
                    CostPrice = getCostPrice[i],
                    IsUnit = getIsUnit[i],
                    Quantily = getQuantily[i]
                };

                var result = await _importApiClient.CreateToImportDetails(data);

                if (result == false)
                {
                    await _importApiClient.DeleteToImport(request.ImportID);
                    TempData["Error"] = MessageModel.AddItemFaled();
                    return RedirectToAction("Index");
                }
                numberSussces++;
            }
            if (numberSussces > 0)
            {
                TempData["Success"] = MessageModel.AddItemSuccessful();
            }
            else
            {
                await _importApiClient.DeleteToImport(request.ImportID);
                TempData["Error"] = MessageModel.AddItemNoSucces();
            }

            return RedirectToAction("Index");
        }
    }
}

G9L.Wedsite/Controllers/ProductController.cs
using G9L.Data.Enum;
using G9L.Data.ViewModel.Catalog.Product;
using G9L.IntergrationAPI.Manufacture;
using G9L.IntergrationAPI.NewFolder;
using G9L.IntergrationAPI.Product;
using G9L.IntergrationAPI.ProductType;
using G9L.Wedsite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace G9L.Wedsite.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IProductTypeApiClient _productTypeApiClient;
        private readonly IManufactureApiClient _manufactureApiClinet;
        private readonly IShoppingCardApiClient _shoppingCardApiClient;
        public ProductController(IProductApiClient productApiClient, IShoppingCardApiClient shoppingCardApiClient , IProductTypeApiClient productTypeApiClient, IManufactureApiClient manufactureApiClient)
        {
            _manufactureApiClinet = manufactureApiClient;
            _productTypeApiClient = productTypeApiClient;
            _productApiClient = productApiClient;
            _shoppingCardApiClient = shoppingCardApiClient;
        }

        public class GetUnitProduct
        {
            public IsUnit ID { get; set; }
            public string Name { get; set; }
        }
        public async Task<IActionResult> Index(string KeyWord, int? ManufactureID ,int? ProductTypeID,string StorageLocations, int PageIndex = 1, int PageSize = 1000)
        {
            var request = new GetManagerProductRequest()
            {
                KeyWord = KeyWord,
                ManufactureID = ManufactureID,
                ProductTypeID = ProductTypeID,
                StorageLocations = StorageLocations,

                PageIndex = PageIndex,
                PageSize = PageSize
            };

            var st = await _productApiClient.GetToProductToName();
            var pt = await _productTypeApiClient.GetToProducTypeOnNameAndID();
            var m = await _manufactureApiClinet.GetToManufacturesOnNameAndID();

            ViewBag.ProductType = pt.Select(x => new SelectListItem()
            {
                Text = x.ProducTypeName,
                Value = x.ProducTypeID.ToString(),
                Selected = ProductTypeID == x.ProducTypeID
            });

            ViewBag.Manufactures = m.Select(x => new SelectListItem()
            {
                Text = x.ManufactureName,
                Value = x.ManufactureID.ToString(),
                Selected = ManufactureID == x.ManufactureID
            });

           
            ViewBag.Product = st.Select(x => new SelectListItem()
            {
                Text = x.ProductName,
                Value = x.ProductName,
                Selected = StorageLocations == x.ProductName
            });

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }

            var data = await _productApiClient.GetListToProduct(request);

            return View(data);
        }

        public async Task<IActionResult> IndexProduct(string KeyWord, int? ManufactureID, int? ProductTypeID, string StorageLocations, int PageIndex = 1, int PageSize = 1000)
        {
            var request = new GetManagerProductRequest()
            {
                KeyWord = KeyWord,
                ManufactureID = ManufactureID,
                ProductTypeID = ProductTypeID,
                StorageLocations = StorageLocations,

                PageIndex = PageIndex,
                PageSize = PageSize
            };
            ViewBag.KeyWord = KeyWord;

            var sc = await _shoppingCardApiClient.CountShoppingCrad();

            var st = await _productApiClient.GetToProductToName();
            var pt = await _productTypeApiClient.GetToProducTypeOnNameAndID();
            var m = await _manufactureApiClinet.GetToManufacturesOnNameAndID();

            ViewBag.ShoppingCard = sc;

            ViewBag.ProductType = pt.Select(x => new SelectListItem()
            {
                Text = x.ProducTypeName,
                Value = x.ProducTypeID.ToString(),
                Selected = ProductTypeID == x.ProducTypeID
            });

            ViewBag.Manufactures = m.Select(x => new SelectListItem()
            {
                Text = x.ManufactureName,
                Value = x.ManufactureID.ToString(),
                Selected = ManufactureID == x.ManufactureID
            });


            ViewBag.Product = st.Select(x => new SelectListItem()
            {
                Text = x.ProductName,
                Value = x.ProductName,
                Selected = StorageLocations == x.ProductName
            });

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }

            var data = await _productApiClient.GetListToProduct(request);

            return View(data);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] GetCreateProductRequest request)
        {
            var result = await _productApiClient.CreateToProduct(request);

            if (result == true)
            {
                TempData["Success"] = MessageModel.AddItemSuccessful();
            }
            else
            {
                TempData["Error"] = MessageModel.AddItemFaled();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Update([FromForm] GetUpdateProductRequest request)
        {

            var result = await _productApiClient.UpdateToProduct(request);

            if (result == true)
            {
                TempData["Success"] = MessageModel.UpdateItemSuccessful();
            }
            else
            {
                TempData["Error"] = MessageModel.UpdateItemFaled();
            }
            return RedirectToAction("Index");
        }
    }
}

G9L.Wedsite/Controllers/ProviderController.cs
using G9L.Data.ViewModel.Catalog.Provider;
using G9L.IntergrationAPI.Provider;
using G9L.Wedsite.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace G9L.Wedsite.Controllers
{
    public class ProviderController : Controller
    {
        private readonly IProviderApiClient _providerApiClient;
        public ProviderController(IProviderApiClient providerApiClient)
        {
            _providerApiClient = providerApiClient;
        }
        public async Task<IActionResult> Index(string KeyWord, int PageIndex = 1, int PageSize = 1000)
        {

            var request = new GetManagerProviderRequest()
            {
                KeyWord = KeyWord,
                PageIndex = PageIndex,
                PageSize = PageSize
            };

            var data = await _providerApiClient.GetListToProvider(request);

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }
            return View(data);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm]GetCreateProviderRequest request)
        {
            var result = await _providerApiClient.CreateToProvider(request);
            if (result == true)
            {
                TempData["Success"] = MessageModel.AddItemSuccessful();
            }
            else
            {
                TempData["Error"] = MessageModel.AddItemFaled();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Update([FromForm] GetUpdateProviderRequest request)
        {
            if (request.NumberPhone == null && request.Address == null && request.ProviderName == null)
                return View();

            var result = await _providerApiClient.UpdateToProvider(request);
            if (result == true)
            {
                TempData["Success"] = MessageModel.UpdateItemSuccessful();
            }
            else
            {
                TempData["Error"] = MessageModel.UpdateItemFaled();
            }
            return RedirectToAction("Index");
        }
    }
}

G9L.Wedsite/Views/Shared/_Footer.cshtml
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website Khánh Nguyên 2022</span>
        </div>
    </div>
</footer>

G9L.Wedsite/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Tìm kiếm"
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                <img class="img-profile rounded-circle" src="img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>

<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Bạn có chắc muốn đăng xuất không?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Chọn "Tiếp tục" để thực hiện quá trình thoát và xóa bộ nhớ</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Quay lại</button>
                <a class="btn btn-primary" href="/Administrator/Login/LogOut">Tiếp tục</a>
            </div>
        </div>
    </div>
</div>

G9L.Wedsite/Views/Shared/_Layout.cshtml
@using G9L.Common.SystemBase

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>Garage 9 Lành</title>

    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

    <style type='text/css'>

        table tr {
            counter-increment: Rownumber;
        }

        table td:first-child + td::before {
            content: counter(Rownumber);
        }
    </style>
</head>


<body id="page-top">
    <!-- Sidenav -->
    <div id="wrapper">
        @await Html.PartialAsync("_Sidebar")
        <!-- Main content -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                @await Html.PartialAsync("_Header")
                <main>
                    <script>
                        setTimeout(function () {
                            $('#msgAlert').fadeOut('slow');
                        }, 600);
                    </script>
                    <div class="row" id="msg">
                        @if (ViewBag.SuccessMessage != null)
                        {
                            <div id="msgAlert" class="alert alert-success alert-dismissible fade show mt--6 ml-3 position-absolute opacity-8" role="alert">
                                <span class="alert-icon"> <i class="fas fa-check-circle"></i></span>
                                <span class="alert-text"><strong>@ViewBag.SuccessMessage</strong></span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                        @if (ViewBag.ErrorMessage != null)
                        {
                            <div id="msgAlert" class="alert alert-danger alert-dismissible fade show  mt--6 ml-3 position-absolute opacity-8" role="alert">
                                <span class="alert-icon"><i class="fas fa-exclamation-triangle"></i></span>
                                <span class="alert-text"><strong> @ViewBag.ErrorMessage</strong></span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }

                    </div>
                </main>
                <!-- Topnav -->
                <div class="content-wrapper">
                    @RenderBody()
                </div>
            </div>
            @await Html.PartialAsync("_Footer")
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    @*<script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>*@

    <script src="https://kit.fontawesome.com/dcd92f06c4.js" crossorigin="anonymous"></script>

</body>

</html>

G9L.Wedsite/Views/Shared/_Sidebar.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Dashboard" asp-action="Index">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fa-solid fa-9"></i>
            <i class="fa-solid fa-l"></i>
        </div>
        <div class="sidebar-brand-text mx-3">GARAGE <BR> 9 LÀNH</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Tổng quan</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Hàng hóa
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa-solid fa-boxes-stacked"></i>
            <span>Sản phẩm</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Danh mục</h6>
                <a class="collapse-item" asp-action="Index" asp-controller="Product">Danh sách sản phẩm</a>
                <a class="collapse-item" asp-controller="ProductType" asp-action="Table">Danh sách loại sản phẩm</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" asp-controller="Manufacture" asp-action="Index">
            <i class="fa-solid fa-truck-ramp-box"></i>
            <span>Nhà sản xuất</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="Provider">
            <i class="fa-solid fa-people-carry-box"></i>
            <span>Nhà cung cấp</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Kinh doanh
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fa-solid fa-chart-pie"></i>
            <span>Báo cáo thống kê</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Danh mục:</h6>
                <a class="collapse-item" href="login.html">Báo cáo tổng hợp</a>
                <a class="collapse-item" href="register.html">Báo cáo doanh thu</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages1"
           aria-expanded="true" aria-controls="collapsePages1">
            <i class="fa-solid fa-file-invoice-dollar"></i>
            <span>Hoạt động kinh doanh</span>
        </a>
        <div id="collapsePages1" class="collapse" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Danh mục:</h6>
                <a class="collapse-item" asp-controller="Import" asp-action="Index">Danh sách nhập hàng</a>
                <a class="collapse-item" asp-controller="Export" asp-action="Index">Danh sách bán hàng</a>
                <a class="collapse-item" href="#">Danh sách nợ</a>
            </div>
        </div>
    </li>
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Cấu hình
    </div>
    <li class="nav-item">
        <a class="nav-link" href="#">
            <i class="fa-solid fa-user-gear"></i>
            <span>Tài khoản quản trị</span>
        </a>
    </li>
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>