G9L.Wedsite/Controllers/ProductController.cs
using G9L.Data.Enum;
using G9L.Data.ViewModel.Catalog.Product;
using G9L.IntergrationAPI.Manufacture;
using G9L.IntergrationAPI.NewFolder;
using G9L.IntergrationAPI.Product;
using G9L.IntergrationAPI.ProductType;
using G9L.Wedsite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace G9L.Wedsite.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IProductTypeApiClient _productTypeApiClient;
        private readonly IManufactureApiClient _manufactureApiClinet;
        private readonly IShoppingCardApiClient _shoppingCardApiClient;
        public ProductController(IProductApiClient productApiClient, IShoppingCardApiClient shoppingCardApiClient , IProductTypeApiClient productTypeApiClient, IManufactureApiClient manufactureApiClient)
        {
            _manufactureApiClinet = manufactureApiClient;
            _productTypeApiClient = productTypeApiClient;
            _productApiClient = productApiClient;
            _shoppingCardApiClient = shoppingCardApiClient;
        }

        public class GetUnitProduct
        {
            public IsUnit ID { get; set; }
            public string Name { get; set; }
        }
        public async Task<IActionResult> Index(string KeyWord, int? ManufactureID ,int? ProductTypeID,string StorageLocations, int PageIndex = 1, int PageSize = 1000)
        {
            var request = new GetManagerProductRequest()
            {
                KeyWord = KeyWord,
                ManufactureID = ManufactureID,
                ProductTypeID = ProductTypeID,
                StorageLocations = StorageLocations,

                PageIndex = PageIndex,
                PageSize = PageSize
            };

            var st = await _productApiClient.GetToProductToName();
            var pt = await _productTypeApiClient.GetToProducTypeOnNameAndID();
            var m = await _manufactureApiClinet.GetToManufacturesOnNameAndID();

            ViewBag.ProductType = pt.Select(x => new SelectListItem()
            {
                Text = x.ProducTypeName,
                Value = x.ProducTypeID.ToString(),
                Selected = ProductTypeID == x.ProducTypeID
            });

            ViewBag.Manufactures = m.Select(x => new SelectListItem()
            {
                Text = x.ManufactureName,
                Value = x.ManufactureID.ToString(),
                Selected = ManufactureID == x.ManufactureID
            });

           
            ViewBag.Product = st.Select(x => new SelectListItem()
            {
                Text = x.ProductName,
                Value = x.ProductName,
                Selected = StorageLocations == x.ProductName
            });

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }

            var data = await _productApiClient.GetListToProduct(request);

            return View(data);
        }

        public async Task<IActionResult> IndexProduct(string KeyWord, int? ManufactureID, int? ProductTypeID, string StorageLocations, int PageIndex = 1, int PageSize = 1000)
        {
            var request = new GetManagerProductRequest()
            {
                KeyWord = KeyWord,
                ManufactureID = ManufactureID,
                ProductTypeID = ProductTypeID,
                StorageLocations = StorageLocations,

                PageIndex = PageIndex,
                PageSize = PageSize
            };
            ViewBag.KeyWord = KeyWord;

            var sc = await _shoppingCardApiClient.CountShoppingCrad();

            var st = await _productApiClient.GetToProductToName();
            var pt = await _productTypeApiClient.GetToProducTypeOnNameAndID();
            var m = await _manufactureApiClinet.GetToManufacturesOnNameAndID();

            ViewBag.ShoppingCard = sc;

            ViewBag.ProductType = pt.Select(x => new SelectListItem()
            {
                Text = x.ProducTypeName,
                Value = x.ProducTypeID.ToString(),
                Selected = ProductTypeID == x.ProducTypeID
            });

            ViewBag.Manufactures = m.Select(x => new SelectListItem()
            {
                Text = x.ManufactureName,
                Value = x.ManufactureID.ToString(),
                Selected = ManufactureID == x.ManufactureID
            });


            ViewBag.Product = st.Select(x => new SelectListItem()
            {
                Text = x.ProductName,
                Value = x.ProductName,
                Selected = StorageLocations == x.ProductName
            });

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }

            var data = await _productApiClient.GetListToProduct(request);

            return View(data);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] GetCreateProductRequest request)
        {
            var result = await _productApiClient.CreateToProduct(request);

            if (result == true)
            {
                TempData["Success"] = MessageModel.AddItemSuccessful();
            }
            else
            {
                TempData["Error"] = MessageModel.AddItemFaled();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Update([FromForm] GetUpdateProductRequest request)
        {

            var result = await _productApiClient.UpdateToProduct(request);

            if (result == true)
            {
                TempData["Success"] = MessageModel.UpdateItemSuccessful();
            }
            else
            {
                TempData["Error"] = MessageModel.UpdateItemFaled();
            }
            return RedirectToAction("Index");
        }
    }
}

G9L.Wedsite/Controllers/ShoppingCardController.cs
using G9L.Data.ViewModel.Common;
using G9L.IntergrationAPI.NewFolder;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace G9L.Wedsite.Controllers
{
    public class ShoppingCardController : Controller
    {
        private readonly IShoppingCardApiClient _shoppingCardApiClient;
        public ShoppingCardController(IShoppingCardApiClient shoppingCardApiClient)
        {
            _shoppingCardApiClient = shoppingCardApiClient;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _shoppingCardApiClient.GetListToShoppingCart();

            if (TempData["Success"] != null)
            {
                ViewBag.SuccessMessage = TempData["Success"];
            }
            if (TempData["Error"] != null)
            {
                ViewBag.ErrorMessage = TempData["Error"];
            }
            return View(data);
        }
    }
}

G9L.Wedsite/Views/Product/IndexProduct.cshtml
@using G9L.Data.ViewModel.Common
@using G9L.Common.SystemBase
@using G9L.Data.Enum
@model PagedResult<G9L.Data.ViewModel.Catalog.Product.GetManagerProductViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main>
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">Danh sách chi tiết sản phẩm</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">

                            <a asp-controller="ShoppingCard" asp-action="Index" class="btn badge-pill badge-primary">
                                <span> <i class="fa-solid fa-cart-flatbed"></i></span>
                                <span class="badge badge-md badge-circle badge-floating badge-danger border-white">@ViewBag.ShoppingCard</span>
                            </a>
                    </div>

                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="header-body">
                <form method="get" asp-controller="Product" asp-action="IndexProduct">
                    <div class="row align-items-center">
                        <div class="col-lg-2 col-7">
                            <div class="form-group">
                                <label for="example-search-input" class="form-control-label text-white">Tìm kiếm</label>
                                <input name="KeyWord" class="form-control" value="@ViewBag.KeyWord" type="search" placeholder="Bạn cần tìm gì...........">
                            </div>
                        </div>
                        <div class="col-lg-2 col-7">
                            <div class="form-group">
                                <label for="example-search-input" class="form-control-label text-white">Nhà sản xuất</label>
                                <select name="ManufactureID" onchange="this.form.submit()" asp-items="@ViewBag.Manufactures" class="form-control" id="exampleFormControlSelect1">
                                    <option></option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-2 col-7">
                            <div class="form-group">
                                <label for="example-search-input" class="form-control-label text-white">Loại sản phẩm</label>
                                <select name="ProductTypeID" onchange="this.form.submit()" asp-items="@ViewBag.ProductType" class="form-control" id="exampleFormControlSelect1">
                                    <option></option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-2 col-7">
                            <div class="form-group">
                                <label for="example-search-input" class="form-control-label text-white">Vị trí</label>
                                <select name="StorageLocations" onchange="this.form.submit()" asp-items="@ViewBag.Product" class="form-control" id="exampleFormControlSelect1">
                                    <option></option>
                                </select>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="container-fluid mt--5">
        <div class="row">
            @foreach (var item in Model.Items)
            {

                <div class="col-xl-4 order-xl-2 ">
                    <div class="card card-profile">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="../assets/img/theme/bac_dan_con_lan_NTN.jpg" alt="First slide">
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="h4">
                                            Mã: @item.ID
                                        </h5>
                                    </div>
                                    <div class="col">
                                        <h5 class="h4" style="float: right;">
                                            Vị trí: @item.StorageLocations
                                        </h5>
                                    </div>
                                </div>
                            </div>

                            <div class="text-center">
                                <h5 class="h3">
                                    @item.Name
                                </h5>
                                <div class="h5 font-weight-300">
                                    <i class="ni location_pin mr-2"></i>( <span class="font-weight-bold">ZUZUKI - HUYNHDAI</span> )
                                </div>
                                <div class="container">
                                    <div class="row">
                                        <div class="col">
                                            <h5 class="h4">
                                                Giá: @item.Price
                                            </h5>
                                        </div>
                                        <div class="col">
                                            <h5 class="h4" style="float: right;">

                                                @if (item.Quantily < 3)
                                                {
                                                    <span class="text-red">  SL: @item.Quantily</span>
                                                }
                                                else
                                                {
                                                    <span> SL: @item.Quantily</span>
                                                }

                                            </h5>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <i class="ni education_hat mr-2">Mô tả: @item.Description</i>
                                </div>
                            </div>
                            <div class="container mt-4">
                                <div class="row">
                                    <div class="col">
                                        <button type="button" class="btn btn-default">Chi tiết</button>
                                    </div>
                                    <div class="col" >
                                        <button type="submit" style="float: right;" onclick="addProductInShoppingCard(@item.ID, 1, @item.IsUnit)" class="btn btn-default">Mua</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</main>
<script>
    BaseLocalhost = '@SystemConnection.BaseConnection'

    async function addProductInShoppingCard(ID, SL, Unit) {
        await $.ajax({
            url: BaseLocalhost + '/api/ShoppingCart/CreateOrUpdateToShoppingCart/' + ID + '?Quantily=' + SL + '&IsUnit=' + 1,
            type: 'POST',
            dataType: 'json',
            success: function (data) {
                document.getElementById('msg').innerHTML =
                    `
                             <div class="alert alert-success alert-dismissible fade show mt--6 ml-3 position-absolute opacity-8" role="alert" >
                                 <span class="alert-icon"> <i class="fas fa-check-circle"></i></span>
                                 <span class="alert-text"><strong>@MessageModel.AddItemSussces</strong></span>
                                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                     <span aria-hidden="true">&times;</span>
                                 </button>
                             </div>
                        `;
                /*setTimeout(function () { $('#msg').fadeOut('slow'); }, 900);*/
               /* setTimeout(function () { location.reload(); }, 800);*/
                location.reload();
            },
            error: function () {
                document.getElementById('msg').innerHTML =
                    `
                            <div class="alert alert-danger alert-dismissible fade show  mt--6 ml-3 position-absolute opacity-8" role="alert">
                                <span class="alert-icon"><i class="fas fa-exclamation-triangle"></i></span>
                                <span class="alert-text"><strong>@MessageModel.DeleteItemFaled</strong></span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        `;
                setTimeout(function () { $('#msg').fadeOut('slow'); }, 700);
                console.log('Connect failed');
            },
        });
    };
</script>